spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/banking_test_db
    username: test_user
    password: test_password

  jpa:
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    root: WARN
    com.banking: DEBUG
